services:
  - type: web
    name: ecopackai
    env: python
    pythonVersion: 3.10.13
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_NAME
        value: ecopackai_db_g08k
      - key: DB_USER
        value: ecopackai_db_g08k_user
      - key: DB_PASSWORD
        value: sroOv5SMjlBfHoD9Dz4qNnLepw2Gqpua
      - key: DB_HOST
        value: dpg-d74l1edm5p6s73f9agc0-a
      - key: DB_PORT
        value: "5432"